repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: markdownlint
        additional_dependencies: [mdformat]

# Documentation validation
-   repo: local
    hooks:
    -   id: validate-docs
        name: Validate Documentation
        entry: bash scripts/validate_docs.sh
        language: system
        types: [markdown, yaml, rst, txt]
        pass_filenames: false
        always_run: true
        verbose: true

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.3.23]
        args: [--max-line-length=88, --ignore=E203,W503]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-dateutil]
        args: [--strict, --ignore-missing-imports]
        exclude: ^tests/
