# .readthedocs.yml
version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub

exclude_patterns:
  - .git/
  - .github/
  - .readthedocs/
  - .readthedocs.yml
  - _build/
  - build/
  - dist/
  - tests/
  - venv/
  - .venv/
  - .pytest_cache/
  - .mypy_cache/
  - .hypothesis/
  - .eggs/
  - *.egg-info/
  - .coverage
  - coverage.xml
  - htmlcov/
  - .idea/
  - .vscode/
  - .DS_Store
  - Thumbs.db
  - .ipynb_checkpoints/
  - .python-version
  - .pre-commit-config.yaml
  - .flake8
  - .isort.cfg
  - .coveragerc
  - .gitattributes
  - .gitignore
  - .gitmodules
  - .mailmap
  - .travis.yml
  - .codecov.yml
  - .editorconfig
  - .prettierrc
  - .prettierignore
  - .stylelintrc
  - .stylelintignore
  - .eslintrc
  - .eslintignore
  - .babelrc
  - .babelrc.js
  - .babelrc.json
  - .babelrc.cjs
  - .babelrc.mjs
  - .babelrc.yaml
  - .babelrc.yml
  - .babelrc.json5
