title: Chronovyan
description: Chronovyan Documentation
baseurl: "/Chronovyan.github.io" # the subpath of your site, e.g. /blog
url: "https://chronovyan.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
