# Project Information
site_name: 4ever
site_description: 'A Modern C++ Library for Temporal Programming'
site_author: '4ever Team'
site_url: https://4ever.dev

# Build Configuration
docs_dir: docs
site_dir: site
strict: true
use_directory_urls: true

# Repository
repo_name: '4ever/4ever'
repo_url: https://github.com/4ever/4ever
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright &u00A9 2025 4ever Team. All rights reserved.'

# Theme Configuration
theme:
  name: material
  custom_dir: docs/overrides
  
  # Icons and Logo
  icon:
    logo: material/infinity
  
  # Features
  features:
    # Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.path
    
    # Content
    - toc.integrate
    - header.autohide
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - content.tooltips.blocks
    - content.tooltips.links
  
  # Typography
  font:
    text: Inter
    code: Fira Code
  
  # Color Schemes
  palette:
    # Light Theme
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: '#1A0033'  # Deepest Violet/Near Black
      accent: '#8E24AA'   # Medium Purple
      background: '#FFFFFF'
      surface: '#FAFAFA'
      text:
        primary: '#1A0033'  # Deepest Violet/Near Black
        secondary: '#4A148C' # Darker Purple
    
    # Dark Theme (Default)
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: '#4A148C'   # Darker Purple
      accent: '#D81B60'    # Vibrant Rose
      background: '#1A0033' # Deepest Violet/Near Black
      surface: '#0F001F'   # Slightly lighter than background
      text:
        primary: '#E0E0E0'  # Light Gray for readability
        secondary: '#B0B0B0'

  # Search
  search:
    language: en
    separator: '[-\s]+'
    tokenizer: '\s+'
    min_search_length: 3
    
  # Social Links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/4ever/4ever
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4ever
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/4everlang

# Extra CSS and JavaScript
extra_css:
  - docs/assets/stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.min.js
  - docs/assets/javascripts/theme.js

# Site verification for search engines
# Uncomment and replace with your own verification codes
# extra:
#   google_analytics:
#     tracking: UA-XXXXXXXXX-X
#   verification:
#     google: google-site-verification-code
#     yandex: yandex-verification-code
#     bing: bing-verification-code

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/4ever/4ever
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/forevercode
      name: Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/forevercode
      name: Discord

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - rss:
      match_path: "news/.*\\.md"
      categories:
        - category
      date_from_meta:
        as_creation: date
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  # Macros plugin is disabled as it's not being used and causing warnings
  # - macros:
  #     include_dir: docs/includes/
  #     include_yaml: !ENV [INCLUDE_YAML, []]
  #     j2_block_start_string: '{%-'
  #     j2_block_end_string: '-%}'
  #     j2_variable_start_string: '{{'
  #     j2_variable_end_string: '}}'


# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Build options
docs_dir: docs
use_directory_urls: true
strict: false  # Temporarily disabled to see validation warnings

# Exclude patterns for files and directories
exclude_docs: |
  # Exclude archive directory completely
  archive/**
  
  # Exclude tutorial files with missing dependencies
  tutorials/act1/chapter1/00_arrival_narrative.md
  tutorials/act1/chapter1/README.md
  tutorials/act1/chapter2/README.md
  tutorials/act2/chapter1/README.md
  
  # Exclude reference files with broken links
  reference/stdlib/collections.md
  reference/stdlib/concurrency.md
  reference/stdlib/io.md
  reference/stdlib/math.md
  reference/stdlib/random.md
  reference/stdlib/reflection.md
  reference/stdlib/string.md
  reference/stdlib/temporal.md
  reference/stdlib/testing.md
  reference/stdlib/time.md
  
  # Exclude problematic files
  concepts/concurrency.md
  concepts/temporal_programming.md
  development/contributing.md
  development/contributing/index.md
  examples/hello_world.md
  examples/temporal_examples.md
  examples/index.md
  reference/stdlib/index.md
  
  # Exclude files with broken links
  reference/index.md
  reference/api_reference.md
  guides/getting-started/index.md
  tutorials/act1/README.md
  concepts/index.md
  README.md

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Core Concepts:
    - Overview: core/01_core_concepts.md
    - Language Tour: core/02_language_tour.md
    - Style Guide: core/03_style_guide.md
    - Aethel & Chronon: core/04_aethel_and_chronon.md
    - Variables: core/08_variables_and_data.md
    - Resource Management: core/07_resource_management.md
    - Manifesto: core/Manifesto.md
    - Types: core/06_types.md
    - Resource Management: core/07_resource_management.md
  
  # Guides
  - Guides:
    - Branding: guides/branding.md
    - Best Practices: guides/best_practices.md
    - Temporal Patterns: guides/temporal_patterns.md
  
  # Standard Library
  - Standard Library:
    - Overview: stdlib/00_overview.md
    - Temporal Types: stdlib/01_temporal_types.md
    - Containers: stdlib/02_containers.md
    - Algorithms: stdlib/03_algorithms.md
  
  # Advanced Topics
  - Advanced:
    - Quantum Computing: advanced/quantum_computing.md
    - Performance Tuning: advanced/performance.md
    - Memory Management: advanced/memory_management.md
  
  # Tutorials
  - Tutorials:
    - Interactive Tutorials: tutorials/Interactive Tutorials - The Hands-on Path to Mastery.md
    - Prologue:
      - Phase 0: tutorials/prologue/phase0_accidental_catalyst.md
    - Act 1:
      - Chapter 1: tutorials/act1/chapter1_variables.md
      - Chapter 2: tutorials/act1/chapter2_conditionals.md
      - Chapter 3: tutorials/act1/chapter3_loops.md
      - Chapter 4: tutorials/act1/chapter4_functions.md
      - Chapter 5: tutorials/act1/chapter5_stabilizing_core.md
  - Advanced Topics:
    - Quantum Entanglement: docs/Advanced Quantum Entanglement - The Art of Temporal Interconnection.md
    - Complex Operations: docs/Complex Quantum Operations - The Art of Temporal Mastery.md
    - Advanced Features: docs/advanced_features_design.md
    - Optimization: docs/advanced_optimization_algorithms.md
  - Reference:
    - API Reference: api_reference.md
    - Standard Library: docs/Chronoscript Standard Library Reference.md
    - Language Specification: docs/Chronoscript Language Specification.md
  - Tools & Development:
    - Development Tools: docs/tools/Development Tools - The Art of Temporal Crafting.md
    - File Extensions: docs/tools/File Extensions - The Art of Temporal Expression.md
  - Troubleshooting:
    - FAQ: docs/troubleshooting/FAQ - Common Questions and Answers.md
    - Debugging Guide: docs/troubleshooting/Advanced Debugging - The Art of Temporal Analysis.md
  - Community:
    - Contributing: CONTRIBUTING.md
    - Roadmap: ROADMAP.md
    - Changelog: CHANGELOG.md

# Customization
extra:
  social:
    - { icon: fontawesome/brands/github, link: 'https://github.com/4ever/4ever', name: GitHub }
    - { icon: fontawesome/brands/twitter, link: 'https://twitter.com/4ever', name: Twitter }
    - { icon: fontawesome/brands/discord, link: 'https://discord.gg/4ever', name: Discord }

# Extra CSS/JS
extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/custom.js

# Build options
strict: false
use_directory_urls: true

# Dev server
dev_addr: '127.0.0.1:8000'
