# Project Information
site_name: Chronovyan
site_url: https://chronovyan.github.io/

# Repository
repo_name: Chronovyan/Chronovyan
repo_url: https://github.com/Chronovyan/Chronovyan

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: blue

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - API Reference: api/index.md
  - Contributing: CONTRIBUTING.md

# Plugins
plugins:
  - search
  - minify

# Build options
strict: false  # Disabled to prevent build failures from warnings
use_directory_urls: true

# Ignore common patterns that might cause warnings
ignore_paths:
  - '**/.git/**'
  - '**/node_modules/**'
  - '**/bower_components/**'
  - '**/__pycache__/**'
  - '**/bower_components/**'
  - '**/node_modules/**'
