# Project Information
site_name: Chronovyan
site_url: https://chronovyan.github.io/Chronovyan/
site_author: Chronovyan Team
site_description: A modern C++ library for dates, times, and time zones

# Repository
repo_name: Chronovyan/Chronovyan
repo_url: https://github.com/Chronovyan/Chronovyan
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Chronovyan. Documentation distributed under CC BY 4.0.

# Theme Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  # Features
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - toc.follow

  # Customization
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Examples: getting-started/examples/
  - Guides:
    - Time Zones: guides/timezones.md
    - Best Practices: guides/best-practices.md
    - Performance: guides/performance.md
  - API Reference:
    - Overview: api/reference/index.md
    - Chrono: api/reference/chrono.md
    - Time Zones: api/reference/timezones.md
    - Formatting: api/reference/formatting.md
  - Development:
    - Building: development/building.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
    - Release Process: development/release-process.md
  - Community:
    - Changelog: community/changelog.md
    - Roadmap: community/roadmap.md
    - Code of Conduct: community/code-of-conduct.md

# Custom CSS and JS
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - rss:
      match_path: "news/.*\\.md"
      categories:
        - Release
        - Announcement
      date_from_meta:
        as_creation: date
      date_from_tz: "UTC"

# Development server
dev_addr: 127.0.0.1:8000

# Build options
strict: true
use_directory_urls: true

# Extra context
extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chronovyan/Chronovyan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chronovyan
    - icon: fontawesome/brands/discord
      link: https://discord.gg/chronovyan

# Google Analytics
google_analytics:
  - UA-XXXXX
  - auto

# Sitemap
sitemap:
  hostname: https://chronovyan.github.io/
