# Project Information
site_name: Chronovyan
site_url: https://chronovyan.github.io
site_description: A temporal programming language for weaving narratives across time
site_author: Chronovyan Team
copyright: Copyright &copy; 2025 Chronovyan Team

# Repository
repo_name: Chronovyan/Chronovyan.github.io
repo_url: https://github.com/Chronovyan/Chronovyan.github.io
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/timer-sand
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
  - mermaid2:
      arguments:
        theme: 'default'
        themeCSS: |
          .mermaid { font-family: 'Roboto', sans-serif; }
  - section-index

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Steps: getting-started/first-steps.md
  - API Reference: api.md
  - Examples: 
    - Basic Examples: examples.md
    - Hello World: examples/hello_world.md
  - Contributing: CONTRIBUTING.md

# Theme configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.tabs
    - content.tooltips
    - content.code.select
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - toc.integrate
    - content.tabs.link

  # Customization
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # Font
  font:
    text: Roboto
    code: Roboto Mono

  # Logo and favicon
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  
  # Icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  # Custom CSS and JS
  extra_css:
    - css/extra.css
  extra_javascript:
    - js/extra.js

  # Search
  search:
    language: en
    separator: '[\s\-]+'

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chronovyan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chronovyan

# Copyright
copyright: >-
  Copyright &copy; 2023 Chronovyan Team - 
  <a href="https://github.com/Chronovyan/Chronovyan.github.io/blob/main/LICENSE">
    MIT License
  </a>
