# Project Information
site_name: Chronovyan
site_url: https://chronovyan.github.io/
site_description: A temporal programming language for weaving narratives across time
site_author: Chronovyan Team
copyright: Copyright &copy; 2023 Chronovyan Team

# Repository
repo_name: Chronovyan/Chronovyan.github.io
repo_url: https://github.com/Chronovyan/Chronovyan.github.io
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/timer-sand
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
  - markdownextradata
  - git-authors
  - redirects:
      redirect_maps:
        'index.html': 'getting-started/installation/'
  - mermaid2:
      arguments:
        theme: 'default'
        themeCSS: |
          .mermaid { font-family: 'Roboto', sans-serif; }
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Language Guide:
    - Basics: guides/Getting Started - The Journey of a Temporal Developer.md
    - Core Concepts: core/Core Concepts - The Foundation of Temporal Programming.md
    - Advanced Features: advanced/Advanced Features - The Art of Temporal Mastery.md
  - Tutorials: 
    - Tutorial Roadmap: TUTORIAL_ROADMAP.md
    - Act 1: tutorials/act1/README.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chronovyan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chronovyan

# Copyright
copyright: >-
  Copyright &copy; 2023 Chronovyan Team - 
  <a href="https://github.com/Chronovyan/Chronovyan.github.io/blob/main/LICENSE">
    MIT License
  </a>
