title: Chronovyan
description: A statically-typed temporal programming language
theme: jekyll-theme-cayman

# Optional: Add a logo or custom CSS
# logo: /path/to/logo.png
# google_analytics: UA-XXXXXXX-X
