# Project information
site_name: Forever Code
site_description: 'A Paradigm for Immutable, Persistent, and Perpetual Digital Entities'
site_author: 'Forever Code Team'
site_url: https://forevercode.dev/

# Repository
repo_name: 'ForeverCode/forevercode'
repo_url: 'https://github.com/ForeverCode/forevercode'
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright &copy; 2025 Forever Code Team'

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.path
    - toc.integrate
    - header.autohide
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - content.tooltips.blocks
    - content.tooltips.links
  font:
    text: Inter
    code: Fira Code
  icon:
    logo: material/infinity
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.path
    - toc.integrate
    - header.autohide
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - content.tooltips.blocks
    - content.tooltips.links
  palette:
    # Light theme
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: '#4A148C'  # Deep Purple
      accent: '#8E24AA'   # Purple
      background: '#FFFFFF'
      surface: '#FAFAFA'
      text:
        primary: '#1A0033'  # Almost Black
        secondary: '#4A4A4A'
    # Dark theme
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: '#8E24AA'   # Purple
      accent: '#BA68C8'    # Light Purple
      background: '#1A0033' # Deep Purple
      surface: '#0F001F'
      text:
        primary: '#E0E0E0'
        secondary: '#B0B0B0'

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.min.js
  - assets/javascripts/theme.js

# Site verification for search engines
# Uncomment and replace with your own verification codes
# extra:
#   google_analytics:
#     tracking: UA-XXXXXXXXX-X
#   verification:
#     google: google-site-verification-code
#     yandex: yandex-verification-code
#     bing: bing-verification-code

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ForeverCode/forevercode
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/forevercode
      name: Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/forevercode
      name: Discord

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - rss:
      match_path: "news/.*\.md"
      categories:
        - category
      date_from_meta:
        as_creation: date
        as_last_update_date: last_updated
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - macros:
      include_dir: includes/
      include_yaml: !ENV [INCLUDE_YAML, []]
      j2_block_start_string: '{%-'
      j2_block_end_string: '-%}'
      j2_variable_start_string: '{{'
      j2_variable_end_string: '}}'

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Build options
docs_dir: .
use_directory_urls: true
strict: true
watch:
  - .overrides

# Remove duplicate markdown extensions and plugins
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - markdownextradata
  - awesome-pages
  - section-index
  - macros:
      include_dir: docs/include
  - redirects:
      redirect_maps:
        'old/path': 'new/path'

# Navigation
nav:
  - Home: index.md
  - Getting Started:
      - guides/getting-started/index.md
      - guides/getting-started/installation.md
      - guides/getting-started/first-steps.md
  - Guides:
      - guides/examples/index.md
      - guides/advanced/index.md
  - Reference:
      - reference/language/specification.md
      - reference/stdlib/index.md
  - Development:
      - development/building.md
      - development/contributing.md
      - development/code-style.md
      - development/documentation-guide.md
      - development/style-guide.md
  - Design:
      - design/architecture.md
      - design/compiler.md
      - design/bytecode-format.md
  - Community:
      - community/code-of-conduct.md
      - community/security.md
      - community/roadmap.md
  - About:
      - about/changelog.md
      - about/license.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chronovyan/Chronovyan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chronovyan
    - icon: fontawesome/brands/discord
      link: https://discord.gg/chronovyan

# Extra CSS/JS
extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/custom.js

# Build options
strict: true
use_directory_urls: true

# Dev server
dev_addr: '127.0.0.1:8000'
