name: Deploy Documentation

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  pull_request:  # Optional: Build on PRs for review
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

# Set environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEPLOY_BRANCH: gh-pages  # Branch where the built docs will be deployed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs-requirements.txt

      - name: Build documentation
        run: mkdocs build --strict --site-dir public
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Only deploy from main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false  # Clean the target branch
          full_commit_message: "Deploy docs: ${{ github.sha }}"
