name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-minify-plugin==0.8.0
          pip install ghp-import

      - name: Build site
        run: mkdocs build --strict --verbose

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          ghp-import -n -p -f ./site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}