name: Deploy MkDocs to GitHub Pages

# Simple trigger - run on push to main or manually
on:
  push:
    branches: [main]
  workflow_dispatch:

# Set minimal required permissions
permissions:
  contents: write
  pages: write
  id-token: write

# Allow concurrent runs for faster feedback
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://chronovyan.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-minify-plugin==0.8.0
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-markdownextradata-plugin
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-section-index
          pip install pymdown-extensions
          pip install pygments
      
      - name: Build
        run: |
          mkdocs build --verbose --strict
          # Verify the site directory was created
          ls -la site/ 2>/dev/null || (echo "Site directory not found!" && exit 1)
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: false
          force_orphan: true
          user_name: 'GitHub Action'
          user_email: 'action@github.com'