name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Debug - List files
        run: |
          pwd
          ls -la
          if [ -f mkdocs.yml ]; then
            echo "mkdocs.yml exists"
            cat mkdocs.yml
          else
            echo "mkdocs.yml does not exist"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-git-revision-date-localized-plugin==1.2.0
          pip install mkdocs-minify-plugin==0.8.1
          pip freeze

      - name: Verify MkDocs can run
        run: |
          mkdocs --version
          mkdocs build --verbose --strict

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./site
          keep-files: true

      - name: Deploy with MkDocs
        if: always()
        run: |
          mkdocs gh-deploy --force --verbose