name: Deploy MkDocs to GitHub Pages

# Only run on push to gh-pages-new branch or manually triggered
on:
  push:
    branches:
      - gh-pages-new
    # Only run when documentation files change
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/gh-pages.yml'
      - 'docs_old/**'
  workflow_dispatch:  # Allow manual triggering

# Set permissions for the workflow
permissions:
  contents: write  # Needed to push to the gh-pages branch
  pages: write
  id-token: write

# Cancel any in-progress runs when a new commit is pushed
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://chronovyan.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-minify-plugin==0.8.0
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-markdownextradata-plugin
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-section-index
          pip install pymdown-extensions
          pip install pygments
      
      - name: Build
        run: |
          mkdocs build --verbose --strict
          # Verify the site directory was created
          ls -la site/ 2>/dev/null || (echo "Site directory not found!" && exit 1)
      
      - name: Deploy to GitHub Pages
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: site  # The folder the action should deploy (matches mkdocs default)
          clean: true  # Automatically remove deleted files from the deploy branch
          token: ${{ secrets.GITHUB_TOKEN }}  # Token for the deployment
          # Output the GitHub Pages URL
          repository-name: ${{ github.repository }}
          # Set the deployment URL as an output
          silent: false