name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          echo "Installing MkDocs and plugins..."
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-minify-plugin==0.8.1
          
          # List installed packages for debugging
          pip list
          
          # Check MkDocs version
          mkdocs --version

      - name: Build site
        run: |
          echo "Building MkDocs site..."
          mkdocs build --strict --verbose
          
          # List built files for debugging
          ls -la site/


      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4