name: Deploy MkDocs to GitHub Pages

# Only run on push to gh-pages-new branch or manually triggered
on:
  push:
    branches:
      - gh-pages-new
    # Only run when files in docs/ or mkdocs.yml change
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel any in-progress runs when a new commit is pushed
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.5.3
          pip install mkdocs-material==9.5.3
          pip install mkdocs-minify-plugin==0.8.0
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-markdownextradata-plugin
          pip install mkdocs-mermaid2-plugin
          pip install mkdocs-section-index
          pip install pymdown-extensions
          pip install pygments
      
      - name: Build
        run: mkdocs build --verbose
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Show deployment status
        run: |
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Deployment status: ${{ steps.deployment.outputs.deployment_status }}"