name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write # Needed to checkout code and potentially upload artifact
  pages: write    # Needed for deploying to GitHub Pages
  id-token: write # Needed for trusted publishing to GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest # Linux runner is efficient for this

    environment:
      name: github-pages # Standard environment name for GitHub Pages deployments
      url: ${{ steps.deployment.outputs.page_url }} # URL will be dynamically set by deploy-pages action

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get your repository code

      - name: Set up Python
        uses: actions/setup-python@v5 # Use a recent stable version of setup-python
        with:
          python-version: '3.10' # Specify the Python version you use

      - name: Install MkDocs and its dependencies
        run: |
          python -m pip install --upgrade pip # Ensure pip is up-to-date
          pip install mkdocs==1.5.3 # Install MkDocs
          pip install mkdocs-material==9.5.3 # Install your theme
          pip install mkdocs-git-revision-date-localized-plugin==1.2.0 # Install your plugin
          pip install mkdocs-minify-plugin==0.8.1 # Install your plugin
          pip freeze # Show installed packages for debugging if needed

      - name: Build MkDocs site
        run: mkdocs build --clean --strict # Build the site, clean previous build, enforce strict mode

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5 # Sets up the Pages environment correctly

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4 # Uploads the generated 'site/' directory as an artifact
        with:
          path: './site' # Path to your built MkDocs site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Publishes the uploaded artifact to GitHub Pages
        # No 'github-token' or 'publish-dir' needed here when using configure-pages and upload-pages-artifact
        # 'keep-files: true' is also not typically needed for fresh deployments.